# Generated by Django 3.0.7 on 2020-06-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='BlogModel',
        ),
    ]
